# -*- coding: utf-8 -*-
"""youtube_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vjfFQtTAi_GC0fGte1T8a2829gmNB10
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
# 1. Load the Data
totals_df = pd.read_csv('Totals.csv')
table_df = pd.read_csv('Table data.csv')

# 2. Data Cleaning
# YouTube's 'Table data' always has a 'Total' sum in the first row. We remove it to analyze individual videos.
if table_df.iloc[0]['Content'] == 'Total':
    table_df = table_df.iloc[1:].copy()

# Ensure our number columns are actual numbers, not text
numeric_cols = ['Views', 'Watch time (hours)', 'Subscribers', 'Impressions']
for col in numeric_cols:
    if col in table_df.columns:
        table_df[col] = pd.to_numeric(table_df[col], errors='coerce')

# 3. Print Top 5 Videos by Views
print("🏆 TOP 5 VIDEOS BY VIEWS 🏆")
print("-" * 30)
top_videos = table_df.sort_values(by='Views', ascending=False).head(5)
for index, row in top_videos.iterrows():
    # slice the title to 50 characters so it fits nicely on the screen
    print(f"🎬 {row['Video title'][:50]}... | 👀 {row['Views']} views")

print("\n") # Adds a blank line

# 4. Day of the Week Analysis (The Weekend Spike)
# Convert the 'Date' column into actual calendar dates
totals_df['Date'] = pd.to_datetime(totals_df['Date'])
# Extract the name of the day (Monday, Tuesday, etc.)
totals_df['DayOfWeek'] = totals_df['Date'].dt.day_name()

# Group the views by day and sum them up
views_by_day = totals_df.groupby('DayOfWeek')['Views'].sum()

# Order the days logically from Monday to Sunday
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
views_by_day = views_by_day.reindex(day_order)

# 5. Data Visualization (Creating the Chart)
plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")

# Create a bar chart
sns.barplot(x=views_by_day.index, y=views_by_day.values, palette='coolwarm')

# Add titles and labels
plt.title('Total YouTube Views by Day of the Week', fontsize=16, fontweight='bold')
plt.xlabel('Day of the Week', fontsize=12)
plt.ylabel('Total Views', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()

# Display the chart right here in Colab
plt.show()


# Chart 2: Daily Views Over Time (Line Chart)
plt.figure(figsize=(12, 5))
# use a line plot to show trends over time
sns.lineplot(data=totals_df, x='Date', y='Views', color='purple')
plt.title('Daily Views Over Time (Channel Growth)', fontsize=16, fontweight='bold')
plt.xlabel('Date', fontsize=12)
plt.ylabel('Views', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Chart 3: Top 10 Videos by Views (Horizontal Bar Chart)
plt.figure(figsize=(10, 6))
# Get the top 10 videos
top_10_videos = table_df.sort_values(by='Views', ascending=False).head(10)

# This removes emojis and keeps only letters/numbers/spaces before plotting
top_10_videos['Short Title'] = top_10_videos['Video title'].apply(lambda x: re.sub(r'[^\w\s,:-]', '', str(x))[:40] + '...')
sns.barplot(data=top_10_videos, x='Views', y='Short Title', palette='viridis')
plt.title('Top 10 Most Viewed Origami Videos', fontsize=16, fontweight='bold')
plt.xlabel('Total Views', fontsize=12)
plt.ylabel('') # Leave Y-axis label blank since the titles explain themselves
plt.tight_layout()
plt.show()

# Chart 4: Impressions vs. Views (Scatter Plot)
plt.figure(figsize=(8, 6))
# A scatter plot shows the relationship between two different numbers
sns.scatterplot(data=table_df, x='Impressions', y='Views', color='darkorange', s=100, alpha=0.7)
plt.title('Algorithm Impact: Impressions vs. Views', fontsize=16, fontweight='bold')
plt.xlabel('Impressions (How many times YouTube showed the thumbnail)', fontsize=12)
plt.ylabel('Views', fontsize=12)
plt.tight_layout()
plt.show()